# Generated by Django 2.2.4 on 2019-09-09 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=50, verbose_name='列名')),
                ('column_en_name', models.CharField(max_length=50, null=True, verbose_name='英文名')),
                ('column_index', models.CharField(db_index=True, max_length=10, verbose_name='列索引例如A,B,C,D...AA,AB')),
                ('must', models.BooleanField(default=True, verbose_name='是否必填')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50, verbose_name='项目名称')),
                ('project_text', models.TextField(null=True, verbose_name='项目描述')),
                ('project_table', models.CharField(max_length=200, null=True, verbose_name='用到的表')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=50, verbose_name='excel表明')),
                ('table_en_name', models.CharField(max_length=50, null=True, verbose_name='英文名')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.IntegerField(db_index=True, verbose_name='行索引')),
                ('value', models.CharField(max_length=1000, null=True, verbose_name='值')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myexcel.Column')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myexcel.Project')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myexcel.Table')),
            ],
        ),
        migrations.AddField(
            model_name='column',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myexcel.Table'),
        ),
    ]
