# Generated by Django 2.2.4 on 2019-09-10 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myexcel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_table',
        ),
        migrations.RemoveField(
            model_name='value',
            name='project',
        ),
        migrations.RemoveField(
            model_name='value',
            name='table',
        ),
        migrations.AddField(
            model_name='table',
            name='table_row',
            field=models.IntegerField(default=10, verbose_name='行数'),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_name',
            field=models.CharField(max_length=50, verbose_name='excel表名'),
        ),
        migrations.CreateModel(
            name='ProjectTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myexcel.Project')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myexcel.Table')),
            ],
        ),
        migrations.AddField(
            model_name='value',
            name='project_table',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myexcel.ProjectTable'),
        ),
    ]
