# Generated by Django 2.2.4 on 2019-09-10 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myexcel', '0002_auto_20190910_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='project_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myexcel.ProjectTable'),
        ),
    ]
