# Generated by Django 2.2.4 on 2019-09-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myexcel', '0003_auto_20190910_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='width',
            field=models.IntegerField(default=80, verbose_name='宽度'),
        ),
        migrations.AlterField(
            model_name='column',
            name='column_index',
            field=models.CharField(db_index=True, max_length=10, null=True, verbose_name='列索引例如A,B,C,...'),
        ),
    ]
