# Generated by Django 2.2.4 on 2019-09-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myexcel', '0004_auto_20190915_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='column',
        ),
        migrations.RemoveField(
            model_name='value',
            name='row_index',
        ),
        migrations.AlterField(
            model_name='value',
            name='value',
            field=models.TextField(null=True, verbose_name='值'),
        ),
    ]
